Repository radix-ui/website, pull requests merged in 2020-12, with the labels that each got.

#67 Fix consitent copy
  pages/blog/introducing-radix-primitives.mdx
  pages/primitives/docs/overview/introduction.mdx
Labels: documentation

#68 Fix scrollbar jank on QuickNav (#64)
  layouts/DocsLayout.tsx
  package.json
Labels: bug

#66 Use accessible-icon primitive
  components/BlogPage.tsx
  components/DocsPage.tsx
  components/ExternalIcon.tsx
  components/Footer.tsx
  components/MDXComponents.tsx
  components/PropsTable.tsx
  components/RadixLogo.tsx
  components/ThemeToggle.tsx
  layouts/BlogLayout.tsx
  pages/blog/index.tsx
  pages/design-system/index.tsx
Labels: enhancement

#78 Tooltip docs: Fix import statement
  pages/primitives/docs/components/tooltip.mdx
Labels: documentation

#79 Fix missing Dialog.Root in docs.
  pages/primitives/docs/components/dialog.mdx
Labels: documentation
